Repository nicholas-maltbie/PropHunt, pull requests merged in 2020-12, with the labels that each got.

#155 Client Server Build Patch
  Assets/BuildConfigurations/ClientBaseBuildConfiguration.buildconfiguration
  Assets/BuildConfigurations/ServerBaseBuildConfiguration.buildconfiguration
  Assets/Prefabs/UI/MainMenuScreen.prefab
  Assets/Scripts/Client/Systems/ConnectionSystem.cs
  Assets/Scripts/GameMain.cs
  Assets/Scripts/UI/ConnectAction.cs
  Assets/Tests/EditModeTests/Client/ConnectionSystemTests.cs
  Assets/Tests/EditModeTests/GameFlowTests.cs
  Assets/Tests/EditModeTests/UI/UIActionTests.cs
  Assets/Tests/PlayModeTests/NetworkTests/NetworkIntegrationTests.cs
  Assets/Tests/PlayModeTests/PlayModeTests.asmdef
Labels: bug

#169 Update to Unity2020.2.1f1
  .github/disabled-workflows/activation.yml
  .github/disabled-workflows/build-dev.yml
  .github/disabled-workflows/build-prod.yml
  .github/workflows/tests.yml
  Assets/Assets.index
  Assets/Assets.index.meta
  Assets/BuildConfigurations/ClientBaseBuildConfiguration.buildconfiguration
  Assets/Materials/Black.mat
  Assets/Renderer/UniversalRenderPipelineAsset_Renderer.asset
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/TestRoomScene.unity
  Development.md
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/URPProjectSettings.asset
Labels: refactor

#171 Feature Focus Objects
  Assets/NetCodeGenerated/PropHunt.Generated/PropHunt.Mixed.Components.PlayerViewSerializer.cs
  Assets/Prefabs/Characters/TestCharacter.prefab
  Assets/Prefabs/Environment/Cube.prefab
  Assets/Scripts/Mixed/Components/FocusDetectionComponent.cs
  Assets/Scripts/Mixed/Components/FocusDetectionComponent.cs.meta
  Assets/Scripts/Mixed/Components/FocusTargetComponent.cs
  Assets/Scripts/Mixed/Components/FocusTargetComponent.cs.meta
  Assets/Scripts/Mixed/Components/PlayerViewComponentData.cs
  Assets/Scripts/Mixed/Systems/FocusDetectionSystem.cs
  Assets/Scripts/Mixed/Systems/FocusDetectionSystem.cs.meta
  Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs
  Assets/Scripts/Mixed/Systems/KinematicCharacterCotnrollerInput.cs
  Assets/Scripts/Mixed/Systems/PlayerRotationSystem.cs
  Assets/Scripts/Mixed/Utils.meta
  Assets/Scripts/Mixed/Utils/FilteringClosestHitCollector.cs
  Assets/Scripts/Mixed/Utils/FilteringClosestHitCollector.cs.meta
  Assets/Scripts/Mixed/Utils/KinematicCharacterControllerUtilities.cs
  Assets/Scripts/Mixed/Utils/KinematicCharacterControllerUtilities.cs.meta
  Assets/Scripts/Mixed/Utils/PredictedStateSystem.cs
  Assets/Scripts/Mixed/Utils/PredictedStateSystem.cs.meta
  Assets/Scripts/Mixed/Utils/PredictionManager.cs
  Assets/Scripts/Mixed/Utils/PredictionManager.cs.meta
  Assets/Scripts/Mixed/Utils/SelfFilteringClosestHitCollector.cs
  Assets/Scripts/Mixed/Utils/SelfFilteringClosestHitCollector.cs.meta
  Assets/Tests/EditModeTests/Mixed/FocusDetectionSystemTests.cs
  Assets/Tests/EditModeTests/Mixed/FocusDetectionSystemTests.cs.meta
  Assets/Tests/EditModeTests/Mixed/KCCComponentsTests.cs
  Assets/Tests/EditModeTests/Mixed/KCCInputSystemTests.cs
  Assets/Tests/EditModeTests/Mixed/KCCUtilsTests.cs
  Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCGravityTests.cs
  Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCGroundedTests.cs
  Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCJumpTests.cs
  Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCMovementTests.cs
  Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCPushOverlappingTests.cs
  Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCSnapDownTests.cs
  Assets/Tests/EditModeTests/Mixed/PlayerRotationSystemTests.cs
  Assets/Tests/EditModeTests/Mixed/PredictionManagerTests.cs
Labels: feature

#173 Added Player Team Component
  Assets/NetCodeGenerated/PropHunt.Generated/GhostComponentSerializerCollection.cs
  Assets/NetCodeGenerated/PropHunt.Generated/PropHunt.Mixed.Components.PlayerTeamSerializer.cs
  Assets/NetCodeGenerated/PropHunt.Generated/PropHunt.Mixed.Components.PlayerTeamSerializer.cs.meta
  Assets/Prefabs/Characters/TestCharacter.prefab
  Assets/Scripts/Mixed/Components/PlayerTeamComponent.cs
  Assets/Scripts/Mixed/Components/PlayerTeamComponent.cs.meta
Labels: feature

#174 Feature Highlight Objects
  Assets/Materials/Black.mat
  Assets/Materials/My ProBuilder Default URP.mat
  Assets/Materials/SquareDefaultYellow.mat
  Assets/Prefabs/Environment/Block.prefab
  Assets/Prefabs/Environment/Cube.prefab
  Assets/Renderer/URP_High.asset
  Assets/Renderer/URP_Med.asset
  Assets/Scenes/TestRoomScene.unity
  Assets/Scripts/Client/Systems/HightlightObjectsSystem.cs
  Assets/Scripts/Client/Systems/HightlightObjectsSystem.cs.meta
  Assets/Scripts/MaterialOverrides.meta
  Assets/Scripts/MaterialOverrides/HeartbeatMaterialOverrides.cs
  Assets/Scripts/MaterialOverrides/HeartbeatMaterialOverrides.cs.meta
  Assets/Scripts/Mixed/Components/HighlightableComponent.cs
  Assets/Scripts/Mixed/Components/HighlightableComponent.cs.meta
  Assets/Scripts/Utils.meta
  Assets/Scripts/Utils/ModifyEntityUtilities.cs
  Assets/Scripts/Utils/ModifyEntityUtilities.cs.meta
  Assets/Shaders/LitDOTS.shadergraph
  Assets/Tests/EditModeTests/Client/HightlightObjectsSystemTests.cs
  Assets/Tests/EditModeTests/Client/HightlightObjectsSystemTests.cs.meta
  Assets/Tests/EditModeTests/Utils/ModifyEntityUtilitiesTests.cs
  Assets/Tests/EditModeTests/Utils/ModifyEntityUtilitiesTests.cs.meta
Labels: feature
