Repository nicholas-maltbie/PropHunt, pull requests merged in 2020-09, with the labels that each got.

#63 Refactored and cleaned existing systems
  Assets/Scripts/Authoring/PlayerMovementAuthoringComponent.cs
  Assets/Scripts/Client/Systems/CameraFollowSystem.cs
  Assets/Scripts/Mixed/Commands/JoinGameRequest.cs
  Assets/Scripts/Mixed/Commands/PlayerInput.cs
  Assets/Scripts/Mixed/Components/KinematicCharacterControllerComponents.cs
  Assets/Scripts/Mixed/Components/MaterialIdComponentData.cs
  Assets/Scripts/Mixed/Components/PlayerIdComponentData.cs
  Assets/Scripts/Mixed/Components/PlayerViewComponentData.cs
  Assets/Scripts/Mixed/Components/PushForceComponentData.cs
  Assets/Scripts/Mixed/Components/UpdateMaterialComponentData.cs
  Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs
  Assets/Scripts/Mixed/Systems/KinematicCharacterCotnrollerInput.cs
  Assets/Scripts/Mixed/Systems/PlayerRotationSystem.cs
  Assets/Scripts/Mixed/Systems/PushComponentSystem.cs
  Assets/Scripts/Mixed/Utility/SelfFilteringClosestHitCollector.cs
  Assets/Scripts/Server/Systems/HandleDisconnectSystem.cs
  Assets/Scripts/Server/Systems/JoinGameServerSystem.cs
Labels: refactor

#66 Removed SampleImages Folder to Save Space
  Development.md
  SampleImages/Demo/disconnect.gif
  SampleImages/Demo/kinematic-cc.gif
  SampleImages/Demo/push.gif
  SampleImages/SetupGuide/EditPreferences.png
  SampleImages/SetupGuide/SelectVSCode.png
  SampleImages/SetupGuide/SetupDotNet4.x.png
  SampleImages/SetupGuide/UnityComplete.png
  SampleImages/SetupGuide/UnityLoad.png
  SampleImages/SetupGuide/UnityProjects.png
  SampleImages/SetupGuide/vstu_scripting-runtime-version.png
Labels: refactor

#64 Automated Github Build Actions
  .github/disabled-workflows/build-dev.yml
  .github/workflows/build-prod.yml
  .github/workflows/tests.yml
  .gitignore
  Assets/Editor.meta
  Assets/Editor/DevelopmentBuilder.cs
  Assets/Editor/DevelopmentBuilder.cs.meta
  Assets/Editor/ProdBuilder.cs
  Assets/Editor/ProdBuilder.cs.meta
Labels: workflow

#54 Basic Testing Framework
  .gitignore
  Assets/Plugins.meta
  Assets/Plugins/Castle.Core.dll
  Assets/Plugins/Castle.Core.dll.meta
  Assets/Plugins/Castle.Core.xml
  Assets/Plugins/Castle.Core.xml.meta
  Assets/Plugins/Moq.dll
  Assets/Plugins/Moq.dll.meta
  Assets/Plugins/Moq.xml
  Assets/Plugins/Moq.xml.meta
  Assets/Plugins/README.md
  Assets/Plugins/README.md.meta
  Assets/Plugins/System.Threading.Tasks.Extensions.dll
  Assets/Plugins/System.Threading.Tasks.Extensions.dll.meta
  Assets/Plugins/System.Threading.Tasks.Extensions.xml
  Assets/Plugins/System.Threading.Tasks.Extensions.xml.meta
  Assets/ScriptableObjects/PropHunt.Scriptable.asmdef
  Assets/ScriptableObjects/PropHunt.Scriptable.asmdef.meta
  Assets/Scripts/Authoring/PlayerViewAuthoringComponent.cs
  Assets/Scripts/Client/Systems/CameraFollowSystem.cs
  Assets/Scripts/Mixed/Components/PlayerViewComponentData.cs
  Assets/Scripts/PropHunt.asmdef
  Assets/Scripts/PropHunt.asmdef.meta
  Assets/Tests.meta
  Assets/Tests/EditModeTests.meta
  Assets/Tests/EditModeTests/Client.meta
  Assets/Tests/EditModeTests/Client/CameraFollowSystemTests.cs
  Assets/Tests/EditModeTests/Client/CameraFollowSystemTests.cs.meta
  Assets/Tests/EditModeTests/EditModeTests.asmdef
  Assets/Tests/EditModeTests/EditModeTests.asmdef.meta
  Assets/Tests/Utils.meta
  Assets/Tests/Utils/ECSTestsFixture.cs
  Assets/Tests/Utils/ECSTestsFixture.cs.meta
  Assets/Tests/Utils/PropHunt.Tests.Utils.asmdef
  Assets/Tests/Utils/PropHunt.Tests.Utils.asmdef.meta
  Assets/Tests/Utils/TestComponents.cs
  Assets/Tests/Utils/TestComponents.cs.meta
  Packages/manifest.json
  ProjectSettings/Packages/com.unity.testtools.codecoverage/.gitignore
Labels: test

#72 Production Build Patch
  .github/disabled-workflows/build-dev.yml
  .github/workflows/build-prod.yml
  Assets/Editor/Builder.cs
  Assets/Editor/Builder.cs.meta
  Assets/Editor/DevelopmentBuilder.cs
  Assets/Editor/DevelopmentBuilder.cs.meta
  Assets/Editor/Input.meta
  Assets/Editor/Input/ArgumentsParser.cs
  Assets/Editor/Input/ArgumentsParser.cs.meta
  Assets/Editor/ProdBuilder.cs
  Assets/Tests/Utils/PropHunt.Tests.Utils.asmdef
Labels: workflow

#74 Adding dot net format to project workflow.
  .config/dotnet-tools.json
  .editorconfig
  .githooks/post-commit
  .githooks/post-merge
  .githooks/pre-commit
  .githooks/pre-push
  .github/workflows/format.yml
Labels: workflow

#71 Added coverage generation to unity tests
  .github/disabled-workflows/build-dev.yml
  .github/workflows/build-prod.yml
  .github/workflows/tests.yml
Labels: test, workflow

#77 Client No Game Hosting
  Assets/Editor/Builder.cs
  Assets/Scripts/GameMain.cs
Labels: bug

#52 KCC Follow Ground
  Assets/Prefabs/Characters/TestCharacter.prefab
  Assets/Prefabs/Environment/Base.prefab
  Assets/Prefabs/Environment/Base.prefab.meta
  Assets/Prefabs/Environment/HorizontalSpinningCylinder.prefab
  Assets/Prefabs/Environment/HorizontalSpinningCylinder.prefab.meta
  Assets/Prefabs/Environment/SpinningCylinder.prefab
  Assets/Prefabs/Environment/SpinningCylinder.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Authoring/MovingPlatformAuthoringComponent.cs
  Assets/Scripts/Authoring/MovingPlatformAuthoringComponent.cs.meta
  Assets/Scripts/Environment.meta
  Assets/Scripts/Environment/Generated.meta
  Assets/Scripts/Environment/Generated/ExampleMovingPlatform.cs
  Assets/Scripts/Environment/Generated/ExampleMovingPlatform.cs.meta
  Assets/Scripts/Environment/Generated/ExampleMovingPlatformGhostSerializer.cs
  Assets/Scripts/Environment/Generated/ExampleMovingPlatformGhostSerializer.cs.meta
  Assets/Scripts/Environment/Generated/ExampleMovingPlatformGhostUpdateSystem.cs
  Assets/Scripts/Environment/Generated/ExampleMovingPlatformGhostUpdateSystem.cs.meta
  Assets/Scripts/Environment/Generated/HorizontalSpinningCylinderGhostSerializer.cs
  Assets/Scripts/Environment/Generated/HorizontalSpinningCylinderGhostSerializer.cs.meta
  Assets/Scripts/Environment/Generated/HorizontalSpinningCylinderGhostUpdateSystem.cs
  Assets/Scripts/Environment/Generated/HorizontalSpinningCylinderGhostUpdateSystem.cs.meta
  Assets/Scripts/Environment/Generated/HorizontalSpinningCylinderSnapshotData.cs
  Assets/Scripts/Environment/Generated/HorizontalSpinningCylinderSnapshotData.cs.meta
  Assets/Scripts/Environment/Generated/SpinningCylinderGhostSerializer.cs
  Assets/Scripts/Environment/Generated/SpinningCylinderGhostSerializer.cs.meta
  Assets/Scripts/Environment/Generated/SpinningCylinderGhostUpdateSystem.cs
  Assets/Scripts/Environment/Generated/SpinningCylinderGhostUpdateSystem.cs.meta
  Assets/Scripts/Environment/Generated/SpinningCylinderSnapshotData.cs
  Assets/Scripts/Environment/Generated/SpinningCylinderSnapshotData.cs.meta
  Assets/Scripts/Generated/GhostDeserializerCollection.cs
  Assets/Scripts/Generated/GhostSerializerCollection.cs
  Assets/Scripts/Mixed/Components/KinematicCharacterControllerComponents.cs
  Assets/Scripts/Mixed/Components/MovementTrackingComponent.cs
  Assets/Scripts/Mixed/Components/MovementTrackingComponent.cs.meta
  Assets/Scripts/Mixed/Components/MovingPlatformComponentData.cs
  Assets/Scripts/Mixed/Components/MovingPlatformComponentData.cs.meta
  Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs
  Assets/Scripts/Mixed/Systems/MovementTrackingSystem.cs
  Assets/Scripts/Mixed/Systems/MovementTrackingSystem.cs.meta
  Assets/Scripts/Mixed/Systems/MovingPlatformSystem.cs
  Assets/Scripts/Mixed/Systems/MovingPlatformSystem.cs.meta
  SampleImages/Demo/FollowGround.gif
Labels: feature

#80 Pre-Commit and formatting update
  .githooks/pre-commit
  Assets/Scripts/GameMain.cs
Labels: refactor

#82 Dotnet Githooks Contributing Update
  Contributing.md
  Development.md
Labels: documentation

#91 Add optional jump grace time, and cooldown - Closes #34
  Assets/NetCodeGenerated/PropHunt.Generated/PropHunt.Mixed.Components.KCCGroundedSerializer.cs
  Assets/NetCodeGenerated/PropHunt.Generated/PropHunt.Mixed.Components.KCCJumpingSerializer.cs
  Assets/Prefabs/Characters/TestCharacter.prefab
  Assets/Scripts/Authoring/PlayerMovementAuthoringComponent.cs
  Assets/Scripts/Mixed/Components/KinematicCharacterControllerComponents.cs
  Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs
Labels: feature
